/**
 * @file RuntimeEmitter.cpp
 * @brief RuntimeEmitter implementation
 * @author Salvatore Bamundo
 * @date 2026
 * SPDX-License-Identifier: GPL-3.0-or-later
 * SPDX-FileCopyrightText: Copyright (c) 2026 undoRT
 */

#include "codegen/RuntimeEmitter.h"
#include "version.hpp"
#include <algorithm>
#include <cctype>
#include <sstream>

namespace st2cpp::codegen {

namespace {

/**
 * @brief Sentinel passed to a Worker constructor when no isolated CPU is left.
 * @details undoPLC's worker constructor has no "auto" mode: it takes the core
 * to pin to. The runtime therefore reserves the sentinel at generation time and
 * only uses it when the machine has fewer isolated cores than tasks, a
 * condition main() reports before starting anything.
 */
constexpr unsigned kNoCpu = 0xFFFFu;

/// Namespace holding every generated task class, away from both the global
/// undoPLC types and the namespace the ST types live in.
constexpr const char* kRtNamespace = "st2cpp_generated";

/**
 * @brief 1 ms expressed the way the C++ digit separators want it.
 */
std::string formatNanoseconds(long long cycleMs)
{
   const long long ns = cycleMs * 1000000LL;
   std::ostringstream out;
   out << ns;
   return out.str();
}

} // namespace

std::string RuntimeEmitter::foldKey(const std::string& s)
{
   std::string key;
   key.reserve(s.size());
   for (unsigned char c : s) {
      if (!std::isspace(c)) {
         key.push_back(static_cast<char>(std::toupper(c)));
      }
   }
   return key;
}

std::string RuntimeEmitter::sanitize(const std::string& s)
{
   std::string out;
   out.reserve(s.size());
   for (unsigned char c : s) {
      out.push_back((std::isalnum(c) || c == '_') ? static_cast<char>(c) : '_');
   }
   if (out.empty() || std::isdigit(static_cast<unsigned char>(out.front()))) {
      out.insert(out.begin(), '_');
   }
   return out;
}

std::string RuntimeEmitter::programTypeName(const std::string& normalizedName) const
{
   if (m_ctx.m_namespace.empty()) {
      return normalizedName;
   }
   return m_ctx.m_namespace + "::" + normalizedName;
}

RuntimeEmitter::RuntimeResult RuntimeEmitter::generate(const TranslationUnit& tu, const task::TaskConfig& config)
{
   RuntimeResult result;

   // ---- 1. Resolve every program the configuration names ----
   //
   // The PRG struct is the unit a task calls, so a name that is not a PROGRAM
   // POU is a configuration error, not something to guess at.
   std::vector<std::string> programByFolded;
   bool hasPrograms = false;
   for (const auto& pou : tu.pous) {
      if (pou.kind == POUKind::PROGRAM) {
         hasPrograms = true;
         programByFolded.push_back(foldKey(pou.name));
      }
   }

   const std::vector<task::PlcGroup> groups = task::groupByPlc(config);

   // C++ type of each program, in the spelling the rest of the generator used.
   std::vector<std::string> programTypes;
   programTypes.reserve(programByFolded.size());
   for (const auto& pou : tu.pous) {
      if (pou.kind == POUKind::PROGRAM) {
         programTypes.push_back(m_ctx.normalizeType(pou.name));
      }
   }

   std::ostringstream out;

   // ---- 2. Header ----
   out << "/**\n"
       << " * @file Runtime.cpp\n"
       << " * @brief undoPLC runtime generated by st2cpp " << ST2CPP_VERSION_STRING << " from a task configuration\n"
       << " * @details One UndoMasterTaskBase per PLC instance and one UndoWorkerTaskBase\n"
       << " * per task; every worker calls the run() of the programs it lists, in\n"
       << " * the declared order, once per cycle.\n"
       << " *\n"
       << " * Generated file - do not edit. Regenerate it with st2cpp --tasks.\n"
       << " */\n\n";

   if (hasPrograms) {
      out << "#include \"Programs.hpp\"\n";
   }
   out << "#include \"undoTasks.hpp\"\n\n";
   out << "#include <boost/asio/io_context.hpp>\n"
       << "#include <boost/asio/signal_set.hpp>\n\n"
       << "#include <algorithm>\n"
       << "#include <csignal>\n"
       << "#include <cstdint>\n"
       << "#include <iostream>\n"
       << "#include <memory>\n"
       << "#include <string>\n"
       << "#include <vector>\n\n";

   out << "namespace " << kRtNamespace << " {\n\n";

   // ---- 3. CPU resolution helper ----
   out << "/**\n"
       << " * @brief Reserve the first isolated CPU no task has taken yet.\n"
       << " * @details Mirrors the resolution UndoMasterTaskBase::start() performs for\n"
       << " * the Master itself: workers declare their core to the constructor, so the\n"
       << " * runtime has to hand out distinct ones. Returns kNoCpu when the machine\n"
       << " * has fewer isolated cores than tasks.\n"
       << " */\n"
       << "static uint16_t reserveAutomaticCpu(const std::vector<int>& isolated, std::vector<uint16_t>& taken)\n"
       << "{\n"
       << "   for (int cpu : isolated) {\n"
       << "      if (cpu < 0) {\n"
       << "         continue;\n"
       << "      }\n"
       << "      const uint16_t id = static_cast<uint16_t>(cpu);\n"
       << "      if (std::find(taken.begin(), taken.end(), id) == taken.end()) {\n"
       << "         taken.push_back(id);\n"
       << "         return id;\n"
       << "      }\n"
       << "   }\n"
       << "   return static_cast<uint16_t>(" << kNoCpu << "u);\n"
       << "}\n\n";

   // ---- 4. One Worker class per task ----
   for (const task::PlcGroup& group : groups) {
      const std::string plcClass = sanitize(group.plc);
      for (size_t index : group.tasks) {
         const task::TaskEntry& entry = config.tasks[index];
         const std::string taskClass = plcClass + "_" + sanitize(entry.name);

         out << "/**\n"
             << " * @brief Task \"" << entry.name << "\" of PLC \"" << group.plc << "\".\n"
             << " * @details Cycle is inherited from the Master ("
             << group.cycleMs << " ms); priority " << entry.priority << ".\n"
             << " */\n"
             << "class " << taskClass << " : public UndoWorkerTaskBase\n"
             << "{\n"
             << "public:\n"
             << "   " << taskClass << "(UndoMasterTaskBase* master, uint16_t cpuId, uint16_t prio)\n"
             << "      : UndoWorkerTaskBase(master, cpuId, prio)\n"
             << "   {\n"
             << "      _taskName = \"" << group.plc << "." << entry.name << "\";\n"
             << "   }\n\n"
             << "   ~" << taskClass << "() override { shutdownAndJoin(); }\n\n"
             << "protected:\n"
             << "   bool runStartup() override\n"
             << "   {\n"
             << "      UndoLog::getInstance().logRT(LogDomain::PRG,\n"
             << "                                   LOG_INFO,\n"
             << "                                   \"%s: startup on core %u\",\n"
             << "                                   _taskName.c_str(),\n"
             << "                                   _cpuId);\n"
             << "      return true;\n"
             << "   }\n\n"
             << "   bool runWork() override\n"
             << "   {\n";

         if (entry.programs.empty()) {
            out << "      // No program bound to this task.\n";
         }
         for (const std::string& program : entry.programs) {
            // Locate the normalized C++ spelling of the named program.
            const std::string key = foldKey(program);
            for (size_t p = 0; p < programByFolded.size(); ++p) {
               if (programByFolded[p] == key) {
                  out << "      _program_" << programTypes[p] << ".run();\n";
                  break;
               }
            }
         }

         out << "      ++_cycleCount;\n"
             << "      return true;\n"
             << "   }\n\n"
             << "   void runFinish() override\n"
             << "   {\n"
             << "      UndoLog::getInstance().logRT(LogDomain::PRG,\n"
             << "                                   LOG_INFO,\n"
             << "                                   \"%s: finished after %llu cycles\",\n"
             << "                                   _taskName.c_str(),\n"
             << "                                   static_cast<unsigned long long>(_cycleCount));\n"
             << "   }\n\n"
             << "private:\n";
         for (size_t p = 0; p < programByFolded.size(); ++p) {
            bool bound = false;
            for (const std::string& program : entry.programs) {
               if (foldKey(program) == programByFolded[p]) {
                  bound = true;
                  break;
               }
            }
            if (bound) {
               // One instance per task: a program bound to two tasks gets two
               // copies with independent state, as it does per task in TwinCAT.
               out << "   " << programTypeName(programTypes[p]) << " _program_" << programTypes[p] << "{};\n";
            }
         }
         out << "   uint64_t _cycleCount{0};\n"
             << "};\n\n";
      }
   }

   // ---- 5. One Master class per PLC instance ----
   for (const task::PlcGroup& group : groups) {
      const std::string plcClass = sanitize(group.plc);

      out << "/**\n"
          << " * @brief PLC instance \"" << group.plc << "\": owns the cycle its tasks share.\n"
          << " * @details undoPLC drives every worker from a single master cycle, so the\n"
          << " * master runs at the finest cycle any task asked for ("
          << group.cycleMs << " ms) and strictly\n"
          << " * above every worker (priority " << group.masterPriority
          << "), so a task that overruns\n"
          << " * cannot delay the cycle supervising it.\n"
          << " */\n"
          << "class " << plcClass << " : public UndoMasterTaskBase\n"
          << "{\n"
          << "public:\n"
          << "   explicit " << plcClass << "(uint64_t cycleTimeNs) : UndoMasterTaskBase(cycleTimeNs)\n"
          << "   {\n"
          << "      _taskName = \"" << group.plc << "\";\n"
          << "   }\n\n"
          << "   ~" << plcClass << "() override { shutdownAndJoin(); }\n\n"
          << "   /**\n"
          << "    * @brief Construct and register every task.\n"
          << "    * @details Must run before start(): a worker registers itself with the\n"
          << "    * master it is constructed with.\n"
          << "    */\n"
          << "   void createTasks()\n"
          << "   {\n";

      // Only pull the isolated-CPU list in when some task actually has to be
      // assigned a core at run time.
      bool anyAutomaticCpu = false;
      for (size_t index : group.tasks) {
         if (config.tasks[index].cpuAffinity < 0) {
            anyAutomaticCpu = true;
            break;
         }
      }
      if (anyAutomaticCpu) {
         out << "      const std::vector<int>& isolated = UndoSys::getInstance().getIsolatedCpu();\n"
             << "      std::vector<uint16_t> takenCpus;\n";
      } else {
         out << "      // Every task of this PLC pins its own core.\n";
      }

      for (size_t index : group.tasks) {
         const task::TaskEntry& entry = config.tasks[index];
         const std::string taskClass = plcClass + "_" + sanitize(entry.name);
         out << "\n"
             << "      // \"" << entry.name << "\": priority " << entry.priority << ", ";
         if (entry.cpuAffinity < 0) {
            out << "cpu automatic\n"
                << "      _tasks.push_back(std::make_unique<" << taskClass << ">(this, reserveAutomaticCpu(isolated, takenCpus), "
                << entry.priority << "u));\n";
         } else {
            // Record the pinned core only when automatic tasks have to avoid it.
            out << "cpu " << entry.cpuAffinity << "\n";
            if (anyAutomaticCpu) {
               out << "      takenCpus.push_back(" << entry.cpuAffinity << "u);\n";
            }
            out << "      _tasks.push_back(std::make_unique<" << taskClass << ">(this, " << entry.cpuAffinity << "u, " << entry.priority
                << "u));\n";
         }
      }

      out << "   }\n\n"
          << "   const std::vector<std::unique_ptr<UndoWorkerTaskBase>>& tasks() const { return _tasks; }\n\n"
          << "protected:\n"
          << "   bool runStartup() override\n"
          << "   {\n"
          << "      UndoLog::getInstance().logRT(LogDomain::PLC, LOG_INFO, \"%s: startup on core %u\", _taskName.c_str(), _cpuId);\n"
          << "      return true;\n"
          << "   }\n\n"
          << "   void readInputBus() override\n"
          << "   {\n"
          << "      // No fieldbus attached: inputs stay as they are. Assign an undoCore::IoBus\n"
          << "      // with setIoBus() to exchange them with the field each cycle.\n"
          << "   }\n\n"
          << "   void writeOutputBus() override\n"
          << "   {\n"
          << "      // No fieldbus attached: outputs are computed but sent nowhere.\n"
          << "   }\n\n"
          << "   void safeStopHandler() override\n"
          << "   {\n"
          << "      UndoLog::getInstance()\n"
          << "         .logRT(LogDomain::PLC, LOG_ERR, \"%s: SAFE STOP triggered - forcing outputs to safe state\", _taskName.c_str());\n"
          << "   }\n\n"
          << "private:\n"
          << "   std::vector<std::unique_ptr<UndoWorkerTaskBase>> _tasks;\n"
          << "};\n\n";
   }

   out << "} // namespace " << kRtNamespace << "\n\n";

   // main() has to sit at global scope, so bring the generated classes into it
   // rather than qualifying every name at every use.
   out << "// main() must be at global scope: pull the generated task classes into it.\n"
       << "using namespace " << kRtNamespace << ";\n\n";

   // ---- 6. Entry point ----
   size_t totalTasks = 0;
   for (const task::PlcGroup& group : groups) {
      totalTasks += group.tasks.size();
   }
   // One isolated core per master plus one per task.
   const size_t requiredCpus = groups.size() + totalTasks;

   out << "/**\n"
       << " * @brief Start every configured PLC and service the logger until interrupted.\n"
       << " */\n"
       << "int main(int argc, char* argv[])\n"
       << "{\n"
       << "   bool logToConsole = false;\n"
       << "   for (int i = 1; i < argc; ++i) {\n"
       << "      if (std::string(argv[i]) == \"--log2console\") {\n"
       << "         logToConsole = true;\n"
       << "      }\n"
       << "   }\n\n"
       << "   // The main thread is the only non-real-time one: it owns the logger.\n"
       << "   boost::asio::io_context ioc;\n"
       << "   UndoLog& logger = UndoLog::getInstance();\n"
       << "   logger.registerThread();\n"
       << "   logger.init(ioc, logToConsole);\n\n"
       << "   UndoSys& sys = UndoSys::getInstance();\n\n"
       << "   std::cout << \"====================================================\" << std::endl;\n"
       << "   std::cout << \"             st2cpp PLC runtime (undoPLC)          \" << std::endl;\n"
       << "   std::cout << \"====================================================\" << std::endl;\n\n";

   for (const task::PlcGroup& group : groups) {
      out << "   logger.logRT(LogDomain::PLC,\n"
          << "                LOG_INFO,\n"
          << "                \"PLC '%s': %zu task(s), cycle %lld ms, master priority %d\",\n"
          << "                \"" << group.plc << "\",\n"
          << "                static_cast<size_t>(" << group.tasks.size() << "u),\n"
          << "                " << group.cycleMs << "LL,\n"
          << "                " << group.masterPriority << ");\n";
   }
   out << "\n";

   out << "   // One isolated core per PLC master plus one per task.\n"
       << "   const std::vector<int>& isolated = sys.getIsolatedCpu();\n"
       << "   const size_t requiredCpus = " << (groups.size() + totalTasks) << "u;\n"
       << "   if (isolated.size() < requiredCpus) {\n"
       << "      std::cerr << \"[ERROR] This PLC needs " << requiredCpus << " isolated CPUs but only \" << isolated.size()\n"
       << "                << \" are available. Check your GRUB isolcpus= configuration.\" << std::endl;\n"
       << "      return 1;\n"
       << "   }\n\n"
        << "   // Pinning the governor is what makes the cycle deterministic, so a failure here is\n"
        << "   // fatal rather than a warning: a PLC running with an unpinned governor would still\n"
        << "   // appear to work while its jitter is no longer bounded. Root is required to write\n"
        << "   // cpufreq, which is also why SCHED_FIFO is worth having here.\n"
        << "   if (sys.setCpuNominalFrequency(isolated) == -1) {\n"
        << "      std::cerr << \"[ERROR] Cannot pin the isolated CPUs to their nominal frequency.\"\n"
        << "                << \"\\n          Root is needed to write cpufreq, and without it the cycle\"\n"
        << "                << \"\\n          jitter is not bounded, so the PLC is not started.\"\n"
        << "                << std::endl;\n"
        << "      return 1;\n"
        << "   }\n\n";

   for (const task::PlcGroup& group : groups) {
      const std::string plcClass = sanitize(group.plc);
      out << "   // ---- PLC \"" << group.plc << "\" ----\n"
          << "   " << plcClass << " plc_" << plcClass << "(" << formatNanoseconds(group.cycleMs) << "ULL);\n"
          << "   plc_" << plcClass << ".createTasks();\n"
          << "   if (!plc_" << plcClass << ".start(" << group.masterPriority << "u)) {\n"
          << "      std::cerr << \"[ERROR] Failed to start the master task of PLC '" << group.plc << "'.\" << std::endl;\n"
          << "      return 1;\n"
          << "   }\n"
          << "   for (const auto& task : plc_" << plcClass << ".tasks()) {\n"
          << "      if (!task->start()) {\n"
          << "         std::cerr << \"[ERROR] Failed to start task '\" << task->getName() << \"'.\" << std::endl;\n"
          << "         plc_" << plcClass << ".stop();\n"
          << "         return 1;\n"
          << "      }\n"
          << "   }\n"
          << "   plc_" << plcClass << ".waitAllRegistered();\n\n";
   }

   out << "   logger.closeRegistration();\n"
       << "\n"
       << "   // Graceful shutdown on Ctrl+C / SIGTERM, handled on this non-RT thread.\n"
       << "   boost::asio::signal_set signals(ioc, SIGINT, SIGTERM);\n"
       << "   signals.async_wait([&](const boost::system::error_code& ec, int signalNumber) {\n"
       << "      if (!ec) {\n"
       << "         logger.logRT(LogDomain::PLC, LOG_WARNING, \"Termination signal (%d) received. Stopping RT threads...\", signalNumber);\n";
   for (const task::PlcGroup& group : groups) {
      out << "         plc_" << sanitize(group.plc) << ".stop();\n";
   }
    out << "         // Undoing the pinning is best effort: reporting it as an error would be\n"
        << "         // noise on a path that already ran to completion.\n"
        << "         if (!sys.resetCpuFrequency(isolated)) {\n"
        << "            std::cerr << \"-> WARNING: Failed to restore the isolated CPUs to powersave.\" << std::endl;\n"
        << "         }\n"
        << "         ioc.stop();\n"
       << "      }\n"
       << "   });\n\n"
       << "   std::cout << \"[Main] Real-time threads running. Press Ctrl+C to stop.\" << std::endl;\n\n"
       << "   // Blocks here servicing the logger with no polling.\n"
       << "   ioc.run();\n\n"
       << "   std::cout << \"[Main] PLC stopped cleanly.\" << std::endl;\n"
       << "   return 0;\n"
       << "}\n";

   // ---- 7. Validate before returning anything ----
   //
   // Done last so one pass reports every bad reference instead of the first.
   for (const task::PlcGroup& group : groups) {
      for (size_t index : group.tasks) {
         const task::TaskEntry& entry = config.tasks[index];
         for (const std::string& program : entry.programs) {
            const std::string key = foldKey(program);
            bool found = false;
            for (const std::string& known : programByFolded) {
               if (known == key) {
                  found = true;
                  break;
               }
            }
            if (!found) {
               result.errors.push_back("tasks[" + std::to_string(index) + "].programs: '" + program + "' is not a PROGRAM of this workspace");
            }
         }
      }
   }

   if (!result.ok()) {
      result.content.clear();
      return result;
   }

   result.content = out.str();
   return result;
}

} // namespace st2cpp::codegen